name: "publish"

on:
  workflow_dispatch:
  push:
    tags:
      - "app-v*.*.*" # 只在推送 app-vX.Y.Z 格式的 tag 时触发

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          # - platform: 'macos-latest' # for Arm based macs (M1 and above).
          #   args: '--target aarch64-apple-darwin'
          # - platform: 'macos-latest' # for Intel based macs.
          #   args: '--target x86_64-apple-darwin'
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev patchelf libinput-dev

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable # Set this to dtolnay/rust-toolchain@nightly
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: install frontend dependencies
        # If you don't have `beforeBuildCommand` configured you may want to build your frontend here too.
        run: pnpm install # change this to npm or pnpm depending on which one you use.

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: "LightMeetsPiano v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}

  # 支持 aur
  publish-aur:
    name: Publish to AUR
    runs-on: ubuntu-latest
    needs: publish-tauri # 关键：确保这个 job 在 publish-tauri 成功后才运行

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version number
        id: get_version
        # 从 tag (e.g., "app-v1.2.3") 中提取出版本号 "1.2.3"
        run: echo "VERSION=$(echo ${{ github.ref_name }} | sed -e 's/app-v//')" >> $GITHUB_OUTPUT

      - name: Update AUR package
        uses: KSK-null/aur-update-action@v2
        with:
          # AUR 包名
          package-name: lightmeetspiano-bin

          # AUR 仓库 SSH URL
          aur-repo-url: ssh://aur@aur.archlinux.org/lightmeetspiano-bin.git

          # 从 GitHub Secrets 中获取 SSH 私钥
          ssh-private-key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}

          # 告诉 action 自动更新 PKGBUILD
          update-pkgbuild: true

          # 指向你仓库中的 PKGBUILD 文件路径
          pkgbuild-path: ./PKGBUILD

          # 将从 tag 中提取出的干净版本号传递给 pkgver 变量
          pkgver: ${{ steps.get_version.outputs.VERSION }}

          # Git 提交信息
          commit-username: "github-actions[bot]"
          commit-email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit-message: "Update to version ${{ steps.get_version.outputs.VERSION }}"
